# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Mersen' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'mersen' do
    @driver.get('http://127.0.0.1:3000/')
    @driver.find_element(:id, 'n').click
    @driver.find_element(:id, 'n').send_keys('5000')
    @driver.find_element(:name, 'commit').click
  end
end
